### ISSUE TITLE
Unintended bucket attribute name change.

### ISSUE THREAD

**Issue by kristofferknudsen** [gadgetron/gadgetron-matlab#10]
#5 Introduced unexpected renaming of bucket attribute, as `bucket.ref` became `bucket.reference`.

**Comment by ojosephs** [comment]
We have a small amount of code already written using "bucket.ref" and, following by analogy one of your examples with "slice.reference" for a single, reference, acquisition header have used bucket.reference for an acquisition header. We could change these at this stage and it sounds like that would be better than having to make the change later. Would you change +gadgetron/+external/+readers/read_bucket.m to refer to "bucket.reference" and "meta.reference", etc.?

**Comment by kristofferknudsen** [comment]
I guess the core of this issue is that I'm unhappy with the names in the [C++ Bucket](https://github.com/gadgetron/gadgetron/blob/master/toolboxes/mri_core/mri_core_acquisition_bucket.h), such as they are. 

- `bucket.ref` in stead of `bucket.reference` (or `bucket.reference_data`)
- `bucket.waveform` in stead of `bucket.waveforms`

I could conceivably be convinced to keep `bucket.ref`, but waveform (singular) for a collection of waveforms is enough to make me lose my composure-cookie. This is all further poisoned by the fact that while `ref` is a pretty generic name, the contents is almost always calibration data. I don't know why the name is not `calibration`.

How do you feel about:
- `bucket.data` Data as usual.
- `bucket.calibration` Calibration data, as found in the `ref` field on the C++ struct.
- `bucket.waveforms` Waveforms as usual.

With:
- `bucket.ref` as an alias of `bucket.calibration`, for backwards compatibility. In Matlab terms, `ref` would be a Dependent Property that just reads/writes the contents of `bucket.calibration`.

**Comment by ojosephs** [comment]
I think the use of the terminology is historical.

For SENSE reconstructions "reference scan" is the usual term
e.g. https://www.mr-tip.com/serv1.php?type=db1&dbs=SENSE%20reference%20scan

and for GRAPPA both  "reference line" and "(auto-)calibration line" are used
e.g. https://users.fmrib.ox.ac.uk/~jesper/papers/Phanalysis_061024/Griswold2002.pdf

Everyone (in MRI) knows what is meant by a "reference scan" or "receive coil sensitivity reference scan" if you need to be ultra-clear, and would immediately guess what bucket.ref contains.

So thinking it through, I think your suggestion is OK. Or have bucket.calibration as the alias of bucket.ref to conform with the (irritating but pre-existing) C++ field names?

Totally agree about bucket.waveforms.

**Comment by kristofferknudsen** [comment]
All right, sounds like `reference` (and the `ref` alternative) is the way to go. I'll type one up. 

I also note that you'd have to do something else about the acquisition you keep as a reference header. As the bucket is now an object (no longer a struct), you can no longer just add properties (like you did with `reference`). So even if I kept `reference` available, you'd still have to change how you transmit the reference acquisition. I apologize for any inconvenience. 

Best regards, 
Kristoffer

**Comment by ojosephs** [comment]
Thanks, looks fine. No difficulty expected transmitting the reference acq. another way. Oliver
