### ISSUE TITLE
duplicate data : reference and ref are stored 

### ISSUE THREAD

**Issue by aTrotier** [gadgetron/gadgetron-matlab#14]
Hi,
I just installed the last version of gadgetron-matlab (from matlab exchange).

When i launch my reconstruction the reference data is duplicated under the name ref and reference. I see that you have made some modifications about this.

I think it is because I am sending the data to matlab after the accumulate trigger and not after the bucket_to_buffer.

[config.txt](https://github.com/gadgetron/gadgetron-matlab/files/4650137/config.txt)

Aurélien

**Comment by kristofferknudsen** [comment]
The `ref` attribute is an alias of the `reference` attribute; a 'Dependent' property in Matlab parlance. 

While it looks cluttered if printed, there's no actual duplication. 

See #10 for details.
